version: "3.7"

services:
  frontend:
    image: reactjs-app
    build:
      context: ./frontend
    environment: 
      - REACT_APP_SERVICE_HOST=http://localhost:8080 
    ports:
      - "3001:3000"
    depends_on: 
      - backend

  backend:
    image: nodejs-app
    build:
      context: ./backend
    ports:
      - "8080:8080"
